version: '3'

x-adaptive-lb: &adaptive-lb
  image: openresty/openresty:1.21.4.1-0-bionic
  volumes:
    - ./lua:/etc/openresty/lua_modules
    - ./config/openresty.conf:/etc/nginx/template
    - ./log/openresty:/var/log/openresty
    - ./scripts/openrestry-entry.sh:/entry.sh
  depends_on:
    - app
  command: sh -c "envsubst '$$LOG_FILE$$APP_PORT$$LB_PORT$$LB_NAME' < /etc/nginx/template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

services:
  app:
    image: node:14-alpine
    ports:
      - $APP_PORT:$APP_PORT
    volumes:
      - ./dist:/src/app/dist
      - ./node_modules:/src/app/node_modules
      - ./log/app:/src/app/log
    environment:
      APP_HOST: ${APP_HOST}
      APP_PORT: ${APP_PORT}
      APP_INFLIGHT: 10
      APP_DURATION: 1000
      APP_JITTER: 50
      APP_METRICS_FILE: /src/app/log/metrics.log
      APP_METRICS_PERIOD: ${APP_METRICS_PERIOD_MS}
    command: node /src/app/dist/server.js -q

  lb:
    image: nginx
    ports:
      - $LB_PORT:$LB_PORT
    volumes:
      - ./config/nginx.conf:/etc/nginx/templates/nginx.conf.template
      - ./log/nginx:/var/log/nginx
    environment:
      APP_PORT: ${APP_PORT}
      LB_PORT: ${LB_PORT}
      NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx
    depends_on:
      - app

  adaptive-lb:
    <<: *adaptive-lb
    ports:
      - $ADAPTIVE_LB_PORT:$ADAPTIVE_LB_PORT
    environment:
      APP_PORT: ${APP_PORT}
      LB_PORT: ${ADAPTIVE_LB_PORT}
      LOG_FILE: access.log
      LB_NAME: A

  adaptive-lb2:
    ports:
      - $ADAPTIVE_LB_PORT2:$ADAPTIVE_LB_PORT2
    environment:
      APP_PORT: ${APP_PORT}
      LB_PORT: ${ADAPTIVE_LB_PORT2}
      LOG_FILE: access2.log
      LB_NAME: B
    <<: *adaptive-lb

networks:
  default:
    name: app-network
    ipam:
      driver: default
      config:
        - subnet: 172.16.50.0/24
