version: '3'

services:
  app:
    image: node:14-alpine
    ports:
      - $APP_PORT:$APP_PORT
    volumes:
      - ./dist:/src/app/dist
      - ./node_modules:/src/app/node_modules
      - ./log/app:/src/app/log
    environment:
      APP_HOST: ${APP_HOST}
      APP_PORT: ${APP_PORT}
      APP_INFLIGHT: 10
      APP_DURATION: 1000
      APP_JITTER: 50
      APP_METRICS_FILE: /src/app/log/metrics.log
      APP_METRICS_PERIOD: 600000
    command: node /src/app/dist/server.js -q

  lb:
    image: nginx
    ports:
      - $LB_PORT:$LB_PORT
    volumes:
      - ./config/nginx.conf.template:/etc/nginx/templates/nginx.conf.template
      - ./log/nginx:/var/log/nginx
    environment:
      APP_PORT: ${APP_PORT}
      LB_PORT: ${LB_PORT}
      NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx
    depends_on:
      - app

  adaptive-lb:
    image: openresty/openresty
    ports:
      - $ADAPTIVE_LB_PORT:$ADAPTIVE_LB_PORT
    volumes:
      - ./lua:/etc/openresty/lua_modules
      - ./config/openresty.conf.template:/etc/openresty/templates/openresty.conf.template
      - ./log/openresty:/var/log/openresty
    environment:
      APP_PORT: ${APP_PORT}
      LB_PORT: ${ADAPTIVE_LB_PORT}
    depends_on:
      - app

  # lb-exporter:
  #   image: nginx/nginx-prometheus-exporter
  #   ports:
  #     - 9113:9113
  #   depends_on:
  #     - lb
  #   command:
  #     - "-nginx.scrape-uri=http://lb:$LB_PORT/metrics"

networks:
  default:
    name: app-network
    ipam:
      driver: default
      config:
        - subnet: 172.16.50.0/24
