{
 "title": "Demo",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Server in-flight",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "nginx_connections_active", "legendFormat": "Active" },
    { "expr": "nginx_connections_waiting", "legendFormat": "Waiting" },
    {
     "expr": "(rate(nginx_connections_accepted[10s]) - rate(nginx_connections_handled[10s])) / 10",
     "legendFormat": "Abort"
    }
   ]
  },
  {
   "title": "Server throughput",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "log.nginx.status",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "2s", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Server latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "log.nginx.response_time", "id": "1", "type": "avg" }
     ],
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}