setup.template.name: "filebeat"
setup.template.pattern: "filebeat"
setup.kibana:
  host: "kibana:5601"

filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/nginx/*.log
      - /var/log/app/*.log

processors:
  - decode_json_fields:
      fields: ["message"]
      max_depth: 3
      target: "log"
      add_error_key: true

output.elasticsearch:
  hosts: "elasticsearch:9200"
  pipelines:
    - pipeline: "filebeat_nginx"
      when.has_fields:
        - "log.nginx"
    - pipeline: "filebeat_app"
      when.has_fields:
        - "log.app"
  index: "filebeat-%{[agent.version]}"
