# my global config
global:
  scrape_interval: 1s
  evaluation_interval: 1s

  external_labels:
    monitor: "my-project"

scrape_configs:
  # - job_name: "server-nginx"
  #   metrics_path: "/metrics"
  #   params:
  #     format: ["prometheus"]
  #   scheme: http
  #   static_configs:
  #     - targets: ["lb-exporter:9113"]
  - job_name: "server-app"
    metrics_path: "/metrics"
    scheme: http
    static_configs:
      - targets: ["app:8000"]
